stages:
  process_data:
    cmd: python src/process.py
    deps:
      - src/utils/filemanager.py
      - src/utils/processing.py
      - data/raw/bank_tickets.json
      - src/process.py
    params:
      - process.raw_file
    outs:
      - data/processed/
    desc: "Takes the raw JSON file, pulled the column _source and converts the _source JSON to a dataframe.\
            It removed all blank and null rows for the feature column 'complaints what happened' that will \
            will need to further featurize for training/testing data"